const USERS = 'USER_TOGGLE';
const UPDATED_USER = 'UPDATED_USER';
const ALL_USERS_LIST = 'ALL_USERS_LIST';
const SELECTED_USERS = 'SELECTED_USERS';
const CITIES_LIST = 'CITIES_LIST';
const REG_CITIES = 'REG_CITIES';
const UPDATE_APOINTMNT = 'UPDATE_APOINTMNT ';
const APOINTMENT_LOOKING = 'APOINTMENT_LOOKING';
const EDIT_PROFILECITIES = 'EDIT_PROFILECITIES';
const TOKEN = 'TOKEN';
const IEMAIL = 'IEMAIL';
const SEARCH_FRIENDS = 'SEARCH_FRIENDS';
const LOGOUT = 'LOGOUT';
const UPDATE_BADGE = 'UPDATE_BADGE';
const SELECT_FRIENDS = 'SELECT_FRIENDS';
const SELECT_MEMBERS = 'SELECT_MEMBERS';
const SET_GROUP_INFO = 'SET_GROUP_INFO';
const SET_GROUP_STATE = 'SET_GROUP_STATE';
const SET_GROUP_ALL_MEMBERS = 'SET_GROUP_ALL_MEMBERS';
const NULLBADGE = 'NULLBADGE';
export {
  USERS,
  ALL_USERS_LIST,
  SELECTED_USERS,
  LOGOUT,
  IEMAIL,
  UPDATED_USER,
  CITIES_LIST,
  REG_CITIES,
  UPDATE_APOINTMNT,
  EDIT_PROFILECITIES,
  NULLBADGE,
  TOKEN,
  APOINTMENT_LOOKING,
  SEARCH_FRIENDS,
  UPDATE_BADGE,
  SELECT_FRIENDS,
  SELECT_MEMBERS,
  SET_GROUP_INFO,
  SET_GROUP_STATE,
  SET_GROUP_ALL_MEMBERS,
};
