require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'figma_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  # pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  # pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  target 'figma_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # add_flipper_pods!('Flipper' => '0.74.0')
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'figma_app-tvOS' do
  # Pods for figma_app-tvOS

  target 'figma_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
